### ISSUE TITLE
The repo desciption is missing an L

### ISSUE THREAD

**Issue by stathissideris** [mischov/reaver#10]
It reads
>A Cojure library for extracting data from HTML.
when it should be
>A Clojure library for extracting data from HTML.

"Clojure" not "Cojure" :)

**Comment by mischov** [comment]
Wait, Reaver works for Clojure as well as Cojure?

Co-jure is an unstable, impractical, and slow programming language with a set of useless features that together form a complex, incoherent, impotent tool focused on the creation of bugs with friends. 

As you might imagine it's competing with a lot of other programming languages in this space, but I have high hopes for it eventually winning out, due to its most important features:
- Simple Type System: Everything is type Thing, which makes it much easier to figure out type signatures and keeps compilation time down
- Ephemeral Vars: If what you reference doesn't exist that's fine, it probably wouldn't have in a year or two anyway
- Code as Code: All code is in code to improve security and prevent theft- for example `(xkafcnf "einnd, tdkng!")` which is a simple program that... hold on, let me find the key

(Thanks, fixed.)

**Comment by stathissideris** [comment]
Haha, nice! Ironically, I spelt "description" without an `r` in the title of my issue, it appears to be infectious 😄
